import type { Signal } from "@trend-pulse/contracts";

export const sampleSignals: Signal[] = [
  {
    schemaVersion: "signal.v1",
    id: "demo-signal-youtube-001",
    workspaceId: "demo",
    observedAt: "2026-08-29T05:00:00.000Z",
    publishedAt: "2026-08-29T03:30:00.000Z",
    collectedAt: "2026-08-29T05:02:00.000Z",
    normalizedAt: "2026-08-29T05:02:05.000Z",
    source: {
      sourceId: "youtube-demo",
      sourceName: "YouTube",
      sourceType: "video",
      accessMode: "official-api",
      freshness: "near-live",
    },
    geography: "Vietnam",
    market: "Vietnam",
    language: "vi",
    topic: "Short-form game challenge format",
    entities: ["mobile gaming"],
    keywords: ["challenge", "mobile game"],
    hashtags: ["#gaming"],
    creator: "Demo creator cluster",
    contentType: "video",
    metrics: { views: 48200, comments: 670, reachProxy: 48200 },
    dynamics: { velocity: 0.72, acceleration: 0.41, novelty: 0.63 },
    confidence: {
      score: 0.66,
      basis: ["single-source demo", "normalized metadata present"],
    },
    evidence: {
      reference: "DEMO CONTRACT DATA — no live source connected yet",
    },
  },
  {
    schemaVersion: "signal.v1",
    id: "demo-signal-rss-001",
    workspaceId: "demo",
    observedAt: "2026-08-29T04:45:00.000Z",
    publishedAt: "2026-08-29T04:00:00.000Z",
    collectedAt: "2026-08-29T04:47:00.000Z",
    normalizedAt: "2026-08-29T04:47:03.000Z",
    source: {
      sourceId: "rss-demo",
      sourceName: "Publisher RSS",
      sourceType: "publisher",
      accessMode: "rss",
      freshness: "hourly",
    },
    geography: "Global",
    language: "en",
    topic: "Creator-led game discovery",
    entities: ["creators", "mobile gaming"],
    keywords: ["creator", "discovery"],
    hashtags: [],
    contentType: "article",
    metrics: { reachProxy: 12000 },
    dynamics: { velocity: 0.44, acceleration: 0.19, novelty: 0.51 },
    confidence: {
      score: 0.61,
      basis: ["single-source demo", "publisher timestamp present"],
    },
    evidence: {
      reference: "DEMO CONTRACT DATA — no live source connected yet",
    },
  },
];
