import type { SourceRegistryEntry } from "@trend-pulse/contracts";

const VERIFIED_AT = "2026-08-29T07:45:00.000Z";

export const sourceRegistry: SourceRegistryEntry[] = [
  {
    schemaVersion: "source-registry.v1",
    sourceId: "wikimedia-pageviews",
    name: "Wikimedia Analytics / Pageviews",
    family: "cultural-attention",
    description: "Open pageview and top-page metrics for Wikimedia projects; useful as broad cultural-attention corroboration, not a category-specific trend source by itself.",
    homepage: "https://doc.wikimedia.org/generated-data-platform/aqs/analytics-api/",
    sourceType: "culture",
    accessMode: "official-api",
    accessStatus: "operational",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["attention", "cultural-event"],
    coverageTags: ["global", "culture", "entertainment", "public-interest", "gaming", "ai", "xr", "vr"],
    geographies: ["global", "country-limited-endpoints"],
    languages: ["multilingual"],
    queryabilityScore: 4,
    historicalDepth: "Pageview endpoints cover data from 2015; current Trend Pulse connector uses daily top pages.",
    automationFeasibilityScore: 10,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "verified",
    commercialUseNote: "Open API; retain source attribution/evidence and obey Wikimedia API usage guidance.",
    termsNote: "Official Analytics API with documented endpoints.",
    evidenceRefs: [
      "https://doc.wikimedia.org/generated-data-platform/aqs/analytics-api/",
      "https://doc.wikimedia.org/generated-data-platform/aqs/analytics-api/reference/page-views.html",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "registry",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "youtube-data-api",
    name: "YouTube Data API",
    family: "video-creator",
    description: "Video, channel and search metadata useful for content velocity, creator propagation and topic/entity discovery.",
    homepage: "https://developers.google.com/youtube/v3",
    sourceType: "video",
    accessMode: "official-api",
    accessStatus: "ready-needs-credential",
    costTier: "free-tier",
    freshness: "near-live",
    signalKinds: ["content-velocity", "creator", "attention", "brand-competitive"],
    coverageTags: ["global", "gaming", "mobile-games", "ai", "saas", "xr", "vr", "beauty", "consumer", "creator"],
    geographies: ["global", "region-filter-supported"],
    languages: ["multilingual"],
    queryabilityScore: 9,
    historicalDepth: "Search/video metadata availability is endpoint-dependent; Trend Pulse must persist its own observations for baselines.",
    automationFeasibilityScore: 8,
    creatorVisibilityScore: 10,
    communityVisibilityScore: 4,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Use only within YouTube API Services Terms and quota policies; server-side credential handling required.",
    termsNote: "search.list moved into granular quota in June 2026; quotas must be checked in the project console before production collection design.",
    evidenceRefs: [
      "https://developers.google.com/youtube/v3/revision_history",
      "https://developers.google.com/youtube/v3/docs/search/list",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "google-trends-api",
    name: "Google Trends API (alpha)",
    family: "search-demand",
    description: "Consistently scaled search-interest data with geographic breakdowns and up to five years of history, but API access remains limited alpha.",
    homepage: "https://developers.google.com/search/apis/trends",
    sourceType: "search",
    accessMode: "official-api",
    accessStatus: "manual-assisted",
    costTier: "unknown",
    freshness: "daily",
    signalKinds: ["search-demand", "attention", "brand-competitive"],
    coverageTags: ["global", "gaming", "mobile-games", "ai", "saas", "xr", "vr", "beauty", "consumer", "b2b"],
    geographies: ["regions", "sub-regions"],
    languages: ["query-dependent"],
    queryabilityScore: 10,
    historicalDepth: "Rolling five-year window; daily/weekly/monthly/yearly aggregation documented for alpha.",
    automationFeasibilityScore: 3,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "approval-required",
    commercialUseNote: "API is limited to approved alpha testers; use the public Trends UI only as manual-assisted research unless API access is granted.",
    termsNote: "Do not assume production API availability without approved alpha access.",
    evidenceRefs: [
      "https://developers.google.com/search/apis/trends",
      "https://developers.google.com/search/blog/2025/07/trends-api",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "google-ads-keyword-planner",
    name: "Google Ads Keyword Planner API",
    family: "search-demand",
    description: "Keyword ideas, historical search metrics and forecasts with language/geography targeting; useful for search intent and demand context rather than fast social virality.",
    homepage: "https://developers.google.com/google-ads/api/docs/keyword-planning/overview",
    sourceType: "search",
    accessMode: "official-api",
    accessStatus: "ready-needs-credential",
    costTier: "free-tier",
    freshness: "daily",
    signalKinds: ["search-demand", "brand-competitive"],
    coverageTags: ["global", "gaming", "ai", "saas", "xr", "vr", "beauty", "consumer", "b2b", "seo", "paid-media"],
    geographies: ["geo-target-supported"],
    languages: ["language-target-supported"],
    queryabilityScore: 10,
    historicalDepth: "Historical keyword metrics; official docs note historical statistics refresh monthly.",
    automationFeasibilityScore: 6,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Requires Google Ads API onboarding, OAuth, developer token and customer context.",
    termsNote: "Keyword Planning services are capacity limited and should be cached rather than polled as a realtime trend stream.",
    evidenceRefs: [
      "https://developers.google.com/google-ads/api/docs/keyword-planning/overview",
      "https://developers.google.com/google-ads/api/docs/keyword-planning/generate-keyword-ideas",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "gdelt-doc-2",
    name: "GDELT DOC 2.0",
    family: "global-news",
    description: "Large global news search corpus suitable for narrative/event corroboration. Current GitHub-hosted runner path timed out during Stage 03 and remains runtime-deferred.",
    homepage: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    sourceType: "news",
    accessMode: "public-dataset",
    accessStatus: "runtime-deferred",
    costTier: "free",
    freshness: "near-live",
    signalKinds: ["news-narrative", "cultural-event", "brand-competitive"],
    coverageTags: ["global", "gaming", "ai", "saas", "xr", "vr", "beauty", "consumer", "b2b", "news"],
    geographies: ["global"],
    languages: ["multilingual"],
    queryabilityScore: 9,
    historicalDepth: "Large historical news corpus; exact endpoint windows depend on API mode.",
    automationFeasibilityScore: 5,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Open project data, but deployment/runtime and source-retention policies still need production review.",
    termsNote: "Runtime failure is environment-specific, not a source rejection.",
    evidenceRefs: ["https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "registry",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "github-rest",
    name: "GitHub REST API",
    family: "developer-ecosystem",
    description: "Repository, release and ecosystem activity useful for AI/developer/product momentum and competitive technology monitoring.",
    homepage: "https://docs.github.com/en/rest",
    sourceType: "community",
    accessMode: "official-api",
    accessStatus: "planned",
    costTier: "free-tier",
    freshness: "near-live",
    signalKinds: ["developer-ecosystem", "launch-product", "brand-competitive"],
    coverageTags: ["global", "ai", "saas", "developer-tools", "open-source", "xr", "vr", "gaming-tech"],
    geographies: ["global"],
    languages: ["code-and-metadata"],
    queryabilityScore: 9,
    historicalDepth: "Repository/activity history varies by endpoint and repository.",
    automationFeasibilityScore: 8,
    creatorVisibilityScore: 4,
    communityVisibilityScore: 7,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Public API is viable, but Trend Pulse needs its own product connector and rate-limit strategy.",
    termsNote: "Search endpoints have rate limits distinct from core REST resources.",
    evidenceRefs: ["https://docs.github.com/en/rest/rate-limit/rate-limit"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "hacker-news-api",
    name: "Hacker News API",
    family: "tech-community",
    description: "Public near-real-time Hacker News items and rankings useful for AI/startup/developer narrative emergence.",
    homepage: "https://github.com/HackerNews/API",
    sourceType: "community",
    accessMode: "official-api",
    accessStatus: "planned",
    costTier: "free",
    freshness: "near-live",
    signalKinds: ["community", "news-narrative", "launch-product", "developer-ecosystem"],
    coverageTags: ["global", "ai", "saas", "startups", "developer-tools", "technology"],
    geographies: ["global"],
    languages: ["primarily-english"],
    queryabilityScore: 4,
    historicalDepth: "Item history is available by item ID; Trend Pulse should persist snapshots for ranking baselines.",
    automationFeasibilityScore: 9,
    creatorVisibilityScore: 2,
    communityVisibilityScore: 9,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Public API; production use should still review Y Combinator/Hacker News terms and respectful request behavior.",
    termsNote: "Official API documentation describes public data as available in near real time via Firebase.",
    evidenceRefs: ["https://github.com/HackerNews/API"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "arxiv-api",
    name: "arXiv API",
    family: "research",
    description: "Research-paper metadata useful for AI/technical weak signals and scientific narrative context, not consumer virality by itself.",
    homepage: "https://info.arxiv.org/help/api/index.html",
    sourceType: "publisher",
    accessMode: "official-api",
    accessStatus: "planned",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["research", "news-narrative"],
    coverageTags: ["global", "ai", "machine-learning", "computer-science", "xr", "vr", "research"],
    geographies: ["global"],
    languages: ["primarily-english-metadata"],
    queryabilityScore: 8,
    historicalDepth: "Long-running scholarly archive; exact query history depends on category and metadata availability.",
    automationFeasibilityScore: 8,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Use metadata/API in accordance with arXiv API terms and rate guidance; paper-content rights remain separate.",
    termsNote: "Treat as research signal, not marketing trend proof alone.",
    evidenceRefs: ["https://info.arxiv.org/help/api/index.html"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "tiktok-creative-center",
    name: "TikTok Creative Center",
    family: "social-creative",
    description: "Public trend and creative intelligence surface with trending hashtags, top ads, regional popularity and related content insights.",
    homepage: "https://ads.tiktok.com/business/creativecenter/",
    sourceType: "social",
    accessMode: "manual",
    accessStatus: "manual-assisted",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["content-velocity", "creator", "ad-creative", "attention"],
    coverageTags: ["global", "gaming", "mobile-games", "beauty", "consumer", "creator", "culture", "ai"],
    geographies: ["regional-filters"],
    languages: ["market-dependent"],
    queryabilityScore: 7,
    historicalDepth: "UI-dependent trend windows; do not assume historical API depth.",
    automationFeasibilityScore: 2,
    creatorVisibilityScore: 9,
    communityVisibilityScore: 5,
    apiOrFeedAvailable: false,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Use as manual-assisted research until a permitted programmatic data path is verified for this product use case.",
    termsNote: "Creative Center is a public/free product surface; this registry entry does not claim a public trends ingestion API.",
    evidenceRefs: [
      "https://ads.tiktok.com/help/article/creative-center?lang=en",
      "https://ads.tiktok.com/resources/help/article/how-to-use-trends?lang=en",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "reddit-data-api",
    name: "Reddit Data API",
    family: "community",
    description: "High-value community discussion signal, but commercial use requires Reddit permission/contract and approved access.",
    homepage: "https://support.reddithelp.com/hc/en-us/articles/14945211791892-Developer-Platform-Accessing-Reddit-Data",
    sourceType: "community",
    accessMode: "official-api",
    accessStatus: "restricted",
    costTier: "unknown",
    freshness: "near-live",
    signalKinds: ["community", "attention", "brand-competitive"],
    coverageTags: ["global", "gaming", "mobile-games", "ai", "saas", "xr", "vr", "beauty", "consumer", "b2b"],
    geographies: ["community-dependent"],
    languages: ["multilingual"],
    queryabilityScore: 9,
    historicalDepth: "API-dependent and subject to approved use case.",
    automationFeasibilityScore: 2,
    creatorVisibilityScore: 3,
    communityVisibilityScore: 10,
    apiOrFeedAvailable: true,
    complianceStatus: "approval-required",
    commercialUseNote: "Reddit states commercial use requires permission and a contract; do not activate without approval.",
    termsNote: "Approval is required and commercial use is not assumed free.",
    evidenceRefs: [
      "https://support.reddithelp.com/hc/en-us/articles/14945211791892-Developer-Platform-Accessing-Reddit-Data",
      "https://redditinc.com/policies/data-api-terms",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "meta-ad-library",
    name: "Meta Ad Library",
    family: "ad-transparency",
    description: "Searchable active-ad transparency surface useful for competitor creative monitoring; API access and coverage differ by ad category/use case.",
    homepage: "https://www.facebook.com/ads/library/",
    sourceType: "brand",
    accessMode: "manual",
    accessStatus: "manual-assisted",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["ad-creative", "brand-competitive"],
    coverageTags: ["global", "gaming", "ai", "saas", "xr", "vr", "beauty", "consumer", "paid-media"],
    geographies: ["country-filter-supported"],
    languages: ["multilingual"],
    queryabilityScore: 8,
    historicalDepth: "Depends on ad category and jurisdiction; active-ad visibility is the broadest common case.",
    automationFeasibilityScore: 3,
    creatorVisibilityScore: 4,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Start manual-assisted; verify exact Ad Library API eligibility/fields for intended non-political competitive-intelligence use before automating.",
    termsNote: "The public Ad Library supports keyword/advertiser search; API details require access review.",
    evidenceRefs: ["https://www.facebook.com/ads/library/"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "steam-web-api",
    name: "Steamworks Web API",
    family: "game-store",
    description: "Steam store/application metadata useful as supporting PC-game ecosystem and product signal; not a substitute for mobile app-store intelligence.",
    homepage: "https://partner.steamgames.com/doc/webapi_overview",
    sourceType: "other",
    accessMode: "official-api",
    accessStatus: "ready-needs-credential",
    costTier: "free-tier",
    freshness: "daily",
    signalKinds: ["product-store", "launch-product", "brand-competitive"],
    coverageTags: ["global", "gaming", "pc-games", "vr", "xr", "game-publishing"],
    geographies: ["global"],
    languages: ["store-metadata-dependent"],
    queryabilityScore: 7,
    historicalDepth: "Endpoint-dependent; Trend Pulse should persist own snapshots for rank/momentum history.",
    automationFeasibilityScore: 7,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 3,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Some public methods are available; other methods require API keys/partner access. Connector must restrict itself to permitted public/store metadata.",
    termsNote: "Steam documents both public and protected Web API methods.",
    evidenceRefs: [
      "https://partner.steamgames.com/doc/webapi_overview",
      "https://partner.steamgames.com/doc/webapi/IStoreService",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "pocketgamer-biz",
    name: "PocketGamer.biz",
    family: "gaming-publisher",
    description: "Specialist mobile-games industry publication covering publishers, launches, monetization, market moves and industry trends.",
    homepage: "https://www.pocketgamer.biz/",
    sourceType: "publisher",
    accessMode: "manual",
    accessStatus: "manual-assisted",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["news-narrative", "launch-product", "brand-competitive", "product-store"],
    coverageTags: ["global", "gaming", "mobile-games", "game-publishing", "studios", "user-acquisition"],
    geographies: ["global"],
    languages: ["english"],
    queryabilityScore: 5,
    historicalDepth: "Large publication archive; automated retention/query depth not yet verified.",
    automationFeasibilityScore: 4,
    creatorVisibilityScore: 1,
    communityVisibilityScore: 1,
    apiOrFeedAvailable: false,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Treat as manual-assisted/source-research candidate until a current RSS/feed or compliant open-web path is verified.",
    termsNote: "Current publication relevance is verified; automated access is not yet assumed.",
    evidenceRefs: ["https://www.pocketgamer.biz/latest/"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "road-to-vr-rss",
    name: "Road to VR",
    family: "xr-publisher",
    description: "Specialist XR/VR publication with a current full-content RSS feed and section-specific feeds documented by the publisher.",
    homepage: "https://roadtovr.com/",
    sourceType: "publisher",
    accessMode: "rss",
    accessStatus: "planned",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["news-narrative", "launch-product", "product-store", "brand-competitive"],
    coverageTags: ["global", "xr", "vr", "ar", "spatial-computing", "vr-games", "hardware"],
    geographies: ["global"],
    languages: ["english"],
    queryabilityScore: 6,
    historicalDepth: "Publication archive plus chronological RSS; Trend Pulse must persist own trend baselines.",
    automationFeasibilityScore: 9,
    creatorVisibilityScore: 1,
    communityVisibilityScore: 1,
    apiOrFeedAvailable: true,
    complianceStatus: "terms-review-required",
    commercialUseNote: "RSS is explicitly documented by the publisher; production retention/redisplay should still preserve attribution and review site terms.",
    termsNote: "Road to VR documented full-content and section feeds in June 2026.",
    evidenceRefs: [
      "https://roadtovr.com/welcome-to-the-new-road-to-vr/",
      "https://roadtovr.com/about-road-to-vr-contact-tip/",
    ],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "google-play-public-store",
    name: "Google Play public store pages",
    family: "mobile-app-store",
    description: "High-value product/store evidence for mobile games and apps, but no automated Trend Pulse collection path is approved yet.",
    homepage: "https://play.google.com/store/games",
    sourceType: "other",
    accessMode: "open-web",
    accessStatus: "manual-assisted",
    costTier: "free",
    freshness: "daily",
    signalKinds: ["product-store", "launch-product", "brand-competitive"],
    coverageTags: ["global", "mobile-games", "gaming", "apps", "ai", "consumer", "game-publishing"],
    geographies: ["market-dependent"],
    languages: ["market-dependent"],
    queryabilityScore: 7,
    historicalDepth: "Public pages are current-state oriented; Trend Pulse would need its own compliant snapshots for history.",
    automationFeasibilityScore: 2,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 2,
    apiOrFeedAvailable: false,
    complianceStatus: "terms-review-required",
    commercialUseNote: "Manual-assisted only until automated access, robots and applicable terms are reviewed for the exact collection method.",
    termsNote: "Do not scrape solely because pages are public.",
    evidenceRefs: ["https://play.google.com/store/games"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
  {
    schemaVersion: "source-registry.v1",
    sourceId: "appmagic",
    name: "AppMagic",
    family: "mobile-market-intelligence",
    description: "Paid mobile market-intelligence candidate for downloads/revenue/competitive app intelligence; kept as paid-later under FREE-FIRST.",
    homepage: "https://appmagic.rocks/",
    sourceType: "other",
    accessMode: "licensed",
    accessStatus: "paid-later",
    costTier: "paid",
    freshness: "daily",
    signalKinds: ["product-store", "brand-competitive", "attention"],
    coverageTags: ["global", "mobile-games", "gaming", "apps", "game-publishing", "user-acquisition"],
    geographies: ["multi-market"],
    languages: ["app-metadata-dependent"],
    queryabilityScore: 9,
    historicalDepth: "Vendor/product-plan dependent; not validated for the free-first production path.",
    automationFeasibilityScore: 5,
    creatorVisibilityScore: 0,
    communityVisibilityScore: 0,
    apiOrFeedAvailable: false,
    complianceStatus: "approval-required",
    commercialUseNote: "Commercial license/vendor agreement required; do not activate in free-first V1 without budget and contract review.",
    termsNote: "Registry keeps this as a high-value paid-later candidate, not an active dependency.",
    evidenceRefs: ["https://appmagic.rocks/"],
    lastVerifiedAt: VERIFIED_AT,
    researchOrigin: "web-research",
  },
];

export function getSourceById(sourceId: string) {
  return sourceRegistry.find((source) => source.sourceId === sourceId);
}
